#!/usr/bin/env bash
# install nginx and change the default page
sudo apt-get -y update
sudo apt-get install -y nginx
c="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "42i $c" /etc/nginx/sites-available/default
service nginx restart
