#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times but
# in the 9th iteration, display Hi

i=1

while [ $i -le 10 ]
do
    if [[ $i -gt 9 ]]
    then
        echo "Hi"
    fi
    echo "Holberton School"
    i=$(( $i + 1 ))
done
