#!/usr/bin/env bash
# This cript displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)

file="$(ls --format=single-column)"

for i in $file
do
    echo "$i" | cut -d'-' -f2
done
